import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { QUESTION_BANK } from '../src/data/questions/index'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUTPUT_PATH = resolve(__dirname, '../docs/verification-log.md')

function generate(): string {
  const lines: string[] = []
  lines.push('# Verification Log')
  lines.push('')
  lines.push(
    'Auto-generated by `scripts/gen-verification-log.ts` — do not hand-edit. Run `npm run gen:verification-log` to regenerate after changing the question bank.',
  )
  lines.push('')
  lines.push(`Total questions: ${QUESTION_BANK.length}`)
  const verifiedCount = QUESTION_BANK.filter((q) => q.verification.status === 'verified').length
  const flaggedCount = QUESTION_BANK.filter((q) => q.verification.status === 'flagged').length
  lines.push(`Verified: ${verifiedCount} · Flagged: ${flaggedCount} · Unverified: ${QUESTION_BANK.length - verifiedCount - flaggedCount}`)
  lines.push('')
  lines.push('| ID | Domain | Scenario | Status | Reviewer | Method | Date | Notes |')
  lines.push('|---|---|---|---|---|---|---|---|')

  const sorted = [...QUESTION_BANK].sort((a, b) => a.id.localeCompare(b.id))
  for (const q of sorted) {
    const scenario = q.scenarioId === null ? '—' : `S${q.scenarioId}`
    const notes = q.verification.notes?.replace(/\|/g, '\\|') ?? ''
    lines.push(
      `| ${q.id} | D${q.domain} | ${scenario} | ${q.verification.status} | ${q.verification.reviewer} | ${q.verification.method} | ${q.verification.date} | ${notes} |`,
    )
  }
  lines.push('')
  return lines.join('\n')
}

const content = generate()
const checkOnly = process.argv.includes('--check')

if (checkOnly) {
  let existing = ''
  try {
    existing = readFileSync(OUTPUT_PATH, 'utf-8')
  } catch {
    // file doesn't exist yet
  }
  if (existing !== content) {
    console.error(
      'docs/verification-log.md is out of date. Run `npm run gen:verification-log` and commit the result.',
    )
    process.exit(1)
  }
  console.log('docs/verification-log.md is up to date.')
} else {
  writeFileSync(OUTPUT_PATH, content, 'utf-8')
  console.log(`Wrote ${OUTPUT_PATH}`)
}
